version: '3.8'
services:
  dev-db:
    image: postgres:latest
    container_name: myshop-db-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: myshop-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - myshop
networks:
  myshop:
